# Generated by Django 5.0.6 on 2024-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
