# Generated by Django 5.0.6 on 2024-06-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
