# Generated by Django 5.0.6 on 2024-07-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
