# Generated by Django 5.0.6 on 2024-07-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
