# Generated by Django 5.0.6 on 2024-06-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50, unique=True)),
                ('Slug', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='static/categories')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
