# Generated by Django 5.0.6 on 2024-06-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_category_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'categories'},
        ),
    ]
