# Generated by Django 5.0.6 on 2024-07-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
