# Generated by Django 5.0.6 on 2024-08-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_useraddress_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
