# Generated by Django 5.0.6 on 2024-08-12 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_useraddress_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
