# Generated by Django 5.0.6 on 2024-08-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_type',
        ),
    ]
