# Generated by Django 5.0.6 on 2024-06-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_images_productimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.CharField(max_length=500),
        ),
    ]
