# Generated by Django 5.0.6 on 2024-07-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='payment_id',
            field=models.CharField(max_length=50),
        ),
    ]
