# Generated by Django 5.0.6 on 2024-07-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordersub_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='coupon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
