# Generated by Django 5.0.6 on 2024-07-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordermain_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='coupon',
            field=models.IntegerField(null=True),
        ),
    ]
