# Generated by Django 5.0.6 on 2024-08-01 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderaddress'),
        ),
    ]
