# Generated by Django 5.0.6 on 2024-08-13 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='order_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ordermain'),
        ),
    ]
