# Generated by Django 5.0.6 on 2024-08-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_returnrequest_order_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersub',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
