# Generated by Django 5.0.6 on 2024-08-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_ordersub_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersub',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
