# Generated by Django 5.0.6 on 2024-07-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product_name',
        ),
    ]
