# Generated by Django 5.0.6 on 2024-07-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_created_at_alter_products_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
