# Generated by Django 5.0.6 on 2024-07-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_created_at'),
        ('products', '0008_alter_products_updated_at'),
    ]

    operations = [
    ]
